const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let lang='ru', quality='auto', opened=false, audioSource=false;
function defaultPrefs(){return {theme:matchMedia('(prefers-color-scheme: light)').matches?'light':'accent',color:'#000000',glass:false,anim:true,shim:true,blur:0,rainbow:false,performance:false}}
let prefs=defaultPrefs();
try{prefs={...prefs,...JSON.parse(localStorage.getItem('cutload-style')||'{}')}}catch{}
function mixc(a,b,t){const x=parseInt(a.slice(1),16),y=parseInt(b.slice(1),16);return '#'+[16,8,0].map(s=>Math.round(((x>>s)&255)*t+((y>>s)&255)*(1-t)).toString(16).padStart(2,'0')).join('')}
function paint(c=prefs.color){const st=document.body.style;const light=prefs.theme==='light',black=prefs.theme==='amoled';document.body.classList.toggle('th-light',light);document.body.classList.toggle('th-amoled',black);const set=(k,v)=>st.setProperty(k,v);set('--accent',c);set('--accent2',c);set('--accent2h',c);set('--button-text',parseInt(c.slice(1,3),16)*.299+parseInt(c.slice(3,5),16)*.587+parseInt(c.slice(5,7),16)*.114>170?'#17232a':'#fff');set('--bg',light?mixc(c,'#e6ebf0',.42):black?'#000000':mixc(c,'#100c20',.12));set('--panel',light?'#ffffff':black?'#0a0a0a':mixc(c,'#100d19',.16));set('--dim',light?mixc(c,'#6b7a88',.25):mixc(c,'#92909f',.4));set('--hoverbg',light?mixc(c,'#ffffff',.12):mixc(c,'#0d0b13',.22));set('--shimc',mixc(c,'#000000',.4));set('--star-blur',prefs.blur/8+'px');$$('.tp-th').forEach(b=>b.classList.toggle('sel',b.dataset.t===prefs.theme));$$('.accsw[data-c]').forEach(b=>b.classList.toggle('sel',b.dataset.c===prefs.color));$('.tp-th[data-t="accent"] .dot').style.background=`linear-gradient(135deg,${mixc(c,'#ffffff',.7)},${mixc(c,'#000000',.75)})`;if(c===prefs.color){$('#accCustom').value=prefs.color;$('#accCustomDot').style.background=prefs.color;if(document.activeElement!==$('#accCustomHex'))$('#accCustomHex').value=prefs.color.toUpperCase();}}
function savePrefs(){try{localStorage.setItem('cutload-style',JSON.stringify(prefs))}catch{}}
function applyPrefs(){paint();document.body.classList.toggle('liquid-glass',prefs.glass);document.body.classList.toggle('shim-on',prefs.shim);document.body.classList.toggle('noanim',!prefs.anim);$('#glassBtn').classList.toggle('on',prefs.glass);$('#glassBtn').setAttribute('aria-pressed',prefs.glass);$('#animChk').checked=prefs.anim;$('#shimChk').checked=prefs.shim;$('#patBlur').value=prefs.blur;$('#patBlurVal').textContent=prefs.blur+'%';$('#shimLayer').style.display='block';$('#shimLayer').classList.toggle('rainbow',prefs.rainbow);$('#rainbowBtn').classList.toggle('active',prefs.rainbow);savePrefs()}
let rainbowEpoch=performance.now();function tick(t){if(prefs.rainbow&&prefs.anim&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const n=parseInt(prefs.color.slice(1),16);const r=(n>>16)&255,g=(n>>8)&255,b=n&255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let hue=d===0?260:max===r?60*((g-b)/d%6):max===g?60*((b-r)/d+2):60*((r-g)/d+4);hue+=(t-rainbowEpoch)/220;const c=hslHex(hue,.7,.65);paint(c);for(let i=1;i<=6;i++)document.body.style.setProperty('--rb'+i,hslHex(hue+(i-1)*60,.55,.26))}requestAnimationFrame(tick)}function hslHex(h,s,l){h=(h%360+360)%360;const a=s*Math.min(l,1-l);const f=n=>{const k=(n+h/30)%12;return Math.round(255*(l-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0')};return '#'+f(0)+f(8)+f(4)}
$('#settingsBtn').onclick=e=>{e.stopPropagation();const p=$('#accPop');p.classList.toggle('show');p.inert=!p.classList.contains('show');$('#settingsBtn').setAttribute('aria-expanded',!p.inert)};$('#accPop').onclick=e=>{e.stopPropagation();const th=e.target.closest('.tp-th'),sw=e.target.closest('.accsw[data-c]');if(th)prefs.theme=th.dataset.t;if(sw){prefs.color=sw.dataset.c;if(prefs.rainbow)rainbowEpoch=performance.now()}if(e.target.closest('#glassBtn'))prefs.glass=!prefs.glass;if(e.target.closest('#rainbowBtn')){prefs.rainbow=!prefs.rainbow;rainbowEpoch=performance.now()}if(e.target.closest('#accAuto'))prefs=defaultPrefs();if(th||sw||e.target.closest('#glassBtn,#rainbowBtn,#accAuto'))applyPrefs()};document.addEventListener('click',()=>{$('#accPop').classList.remove('show');$('#accPop').inert=true;$('#settingsBtn').setAttribute('aria-expanded','false')});$('#accPop').inert=true;
$('#accCustom').oninput=()=>{prefs.color=$('#accCustom').value;if(prefs.rainbow)rainbowEpoch=performance.now();applyPrefs()};$('#accCustomHex').oninput=()=>{let v=$('#accCustomHex').value;if(!v.startsWith('#'))v='#'+v;if(/^#[0-9a-f]{6}$/i.test(v)){prefs.color=v;if(prefs.rainbow)rainbowEpoch=performance.now();applyPrefs()}};$('#patBlur').oninput=e=>{prefs.blur=+e.target.value;applyPrefs()};$('#animChk').onchange=e=>{prefs.anim=e.target.checked;applyPrefs()};$('#shimChk').onchange=e=>{prefs.shim=e.target.checked;applyPrefs()};
function selectQuality(q){quality=q;$$('.quality').forEach(b=>{const selected=b.dataset.q===q;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected)});document.body.classList.toggle('audio',q==='audio'||audioSource);positionIndicator();updateTimes()}
function positionIndicator(){const b=$('.quality.selected'),i=$('#qualityIndicator');i.style.width=b.offsetWidth+'px';i.style.height=b.offsetHeight+'px';i.style.transform=`translate(${b.offsetLeft}px,${b.offsetTop}px)`}$$('.quality').forEach(b=>b.onclick=()=>selectQuality(b.dataset.q));new ResizeObserver(positionIndicator).observe($('.qualities'));
function showMedia(force){audioSource=force==='audio'||/soundcloud|bandcamp|\.mp3|spotify/i.test($('#url').value);opened=true;document.body.classList.add('expanded');$('.download-card').inert=false;$('#mediaTitle').textContent=audioSource?'teiqo — ведьма':'Как исчезнуть в 2026? (Метод Инсайдера)';$('#mediaMeta').textContent=audioSource?'SoundCloud · 03:42':'Харчеников · 20:54';const coverSymbol=$('.cover span');if(coverSymbol)coverSymbol.textContent=audioSource?'♫':'✦';$('#fragmentCheck').checked=false;document.body.classList.remove('fragment-on');$('#rangeStart').value=0;$('#rangeStart').max=$('#rangeEnd').max=audioSource?222:1254;$('#rangeEnd').value=audioSource?222:1254;$$('.quality').forEach(b=>b.hidden=audioSource&&b.dataset.q!=='audio'&&b.dataset.q!=='auto');selectQuality(audioSource?'audio':'auto');}
$('#linkForm').onsubmit=e=>{e.preventDefault();if(!$('#url').value.trim())$('#url').value='https://www.youtube.com/watch?v=c9ZBpQ0miz8';showMedia()};$('#closeCard').onclick=()=>{opened=false;document.body.classList.remove('expanded','fragment-on');$('.download-card').inert=true;$('#fragmentCheck').checked=false};$('.clear-input').onclick=()=>{$('#url').value='';$('#url').focus()};$('#fragmentCheck').onchange=e=>document.body.classList.toggle('fragment-on',e.target.checked);
function fmt(v){return String(Math.floor(v/60)).padStart(2,'0')+':'+String(Math.floor(v%60)).padStart(2,'0')}function parse(v){const a=v.split(':');return a.length===2&&a.every(n=>/^\d+$/.test(n))?+a[0]*60+(+a[1]):NaN}function updateTimes(){const start=+$('#rangeStart').value,end=+$('#rangeEnd').value,max=+$('#rangeEnd').max;$('#timeline').style.setProperty('--start',start/max*100+'%');$('#timeline').style.setProperty('--end',end/max*100+'%');$('#startTime').value=fmt(start);$('#endTime').value=fmt(end);$('#duration').textContent=fmt(end-start)}$('#rangeStart').oninput=()=>{$('#rangeStart').value=Math.min(+$('#rangeStart').value,+$('#rangeEnd').value-3);updateTimes()};$('#rangeEnd').oninput=()=>{$('#rangeEnd').value=Math.max(+$('#rangeEnd').value,+$('#rangeStart').value+3);updateTimes()};$('#startTime').onchange=()=>{const v=parse($('#startTime').value);if(Number.isFinite(v))$('#rangeStart').value=Math.max(0,Math.min(v,+$('#rangeEnd').value-3));updateTimes()};$('#endTime').onchange=()=>{const v=parse($('#endTime').value);if(Number.isFinite(v))$('#rangeEnd').value=Math.min(+$('#rangeEnd').max,Math.max(v,+$('#rangeStart').value+3));updateTimes()};
$('#timeline').onpointermove=e=>{const r=e.currentTarget.getBoundingClientRect(),p=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));$('.hover-preview').style.left=Math.max(44,Math.min(r.width-44,p*r.width))+'px';$('#hoverTime').textContent=fmt(p*+$('#rangeEnd').max);$('.preview-frame').style.background=`linear-gradient(${Math.floor(p*300)}deg,hsl(${160+p*140} 17% 45%),#232636)`;$('.preview-frame span').textContent=['✦','✧','◈','✺','✦'][Math.min(4,Math.floor(p*5))]};
for(let i=0;i<8;i++){const d=document.createElement('div');d.textContent=['✦','✧','◈'][i%3];$('#filmstrip').append(d)}for(let i=0;i<90;i++){const b=document.createElement('i');b.style.height=(8+Math.abs(Math.sin(i*1.7)*Math.cos(i*.21))*43)+'px';$('#waveform').append(b)}
let toastTimer;function toast(ru,en){$('#toast').textContent=lang==='ru'?ru:en;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}$('#chooseFolder').onclick=()=>toast('Папка сохранения — заглушка для макета','Save location is a design placeholder');$('#downloadBtn').onclick=()=>toast($('#fragmentCheck').checked?'Демо: фрагмент '+$('#startTime').value+' — '+$('#endTime').value:'Демо: файл готов к скачиванию','Demo preview — no actual download');$('#aboutBtn').onclick=()=>toast('cutload · интерактивный макет','cutload · interactive design preview');$('#servicesBtn').onclick=()=>toggleServices();$('#servicesDialog .close').onclick=()=>hideServices();
$$('[data-en]').forEach(el=>el.dataset.ru=el.textContent);const translations={secTheme:'theme',themeAccent:'accent',themeBlack:'black',themeWhite:'white',secAccentColor:'accent color',customColor:'custom color',blurLbl:'background blur: ',secAnim:'animations',animSmooth:'smooth animations',shimToggle:'flowing background',resetDefault:'reset defaults'};$('#langBtn').onclick=()=>{lang=lang==='ru'?'en':'ru';document.documentElement.lang=lang;$('#langBtn').textContent=lang==='ru'?'EN':'RU';$$('[data-en]').forEach(el=>el.textContent=el.dataset[lang]);$$('[data-i18n]').forEach(el=>{if(!el.dataset.original)el.dataset.original=el.textContent;el.textContent=lang==='ru'?el.dataset.original:translations[el.dataset.i18n]||el.dataset.original});requestAnimationFrame(positionIndicator)};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.body.classList.contains('orbit-mode')){$('#accPop').classList.remove('show');$('#accPop').inert=true;if(opened&&!$('#servicesDialog').classList.contains('show'))$('#closeCard').click()}});
// Service URL examples are hints, never submitted automatically.
const examples=[
  'https://www.youtube.com/watch?v=c9ZBpQ0miz8',
  'https://soundcloud.com/teiqo/vedma',
  'https://vimeo.com/76979871',
  'зачем ты это читаешь?',
  'https://www.tiktok.com/@user/video/…',
  'https://www.instagram.com/reel/…',
  'https://vk.com/video…',
  'https://www.facebook.com/watch/?v=…',
  'https://x.com/user/status/…',
  'https://www.twitch.tv/videos/…',
  'https://www.reddit.com/r/videos/comments/…',
  'https://rutube.ru/video/…',
  'https://www.bilibili.com/video/BV…',
  'https://www.dailymotion.com/video/…',
  'https://ok.ru/video/…',
  'https://rumble.com/…',
  'https://artist.bandcamp.com/track/…',
  'https://kick.com/user/clips/…',
  'https://bsky.app/profile/user/post/…',
  'https://www.flickr.com/photos/user/…'
];let exampleIndex=0;let typingTimer;
const easterEggIndex=3;
let easterEggShown=false;try{easterEggShown=sessionStorage.getItem('cutload-easter-egg-shown')==='1'}catch{}
let examplePosition=0,exampleErasing=false;
function animateExamples(){
  clearTimeout(typingTimer);const input=$('#url');
  if(opened||input.value){typingTimer=setTimeout(animateExamples,300);return}
  if(exampleIndex===easterEggIndex&&easterEggShown){exampleIndex++;examplePosition=0;exampleErasing=false}
  const phrase=examples[exampleIndex%examples.length];
  examplePosition+=exampleErasing?-1:1;input.placeholder=phrase.slice(0,examplePosition);
  let delay=exampleErasing?22:42;
  if(!exampleErasing&&examplePosition>=phrase.length){exampleErasing=true;delay=1800;if(exampleIndex===easterEggIndex){try{sessionStorage.setItem('cutload-easter-egg-shown','1')}catch{}}}
  else if(exampleErasing&&examplePosition<=0){if(exampleIndex===easterEggIndex)easterEggShown=true;exampleErasing=false;examplePosition=0;exampleIndex=(exampleIndex+1)%examples.length;delay=300}
  typingTimer=setTimeout(animateExamples,delay);
}
animateExamples();applyPrefs();requestAnimationFrame(tick);updateTimes();
